authentication/urls.py
from django.contrib import admin
from django.urls import path
from authentication.views import (SignUpView,SignInView, SignOutView, PRView, PRConfirm, PRDone, PRComplete)
                                    # , PRDone, PRConfirm, PRComplete)

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup_view'),
    path('', SignInView.as_view(), name='signin_view'),
    path('signout/', SignOutView.as_view(), name='signout_view'),
    path('password/reset', PRView.as_view(), name = 'password_reset'),
    path('password/reset/done/', PRDone.as_view(), name= 'password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>', PRConfirm.as_view(), name= 'password_reset_confirm'),
    path('password/reset/complete/', PRComplete.as_view(), name= 'password_reset_complete'),

]                                                                                                                                            

core/urls.py
from django.urls import path
from core.views import FeedView
from django.contrib.auth.decorators import login_required

urlpatterns = [
   path('', login_required(FeedView.as_view()), name="feed_view"),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls'), name='authentication'),
    path('feed/',include('core.urls'), name = 'core'),
]

authentication/models.py
from django.db import models

# Create your models here.

common/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from user.manager import CustomUserManager
# Create your models here.
# class User(AbstractUser):
#     picture = models.ImageField(upload_to='profile_pictures')

#     USERNAME_FIELD = 'username'
#     REQUIRED_FIELDS = []

#     # objects = AbstractUserManager()

#     def create_superuser(self, email, password):
#         """
#         Creates and saves a superuser with the given email and password.
#         """
#         user = self.create_user(
#             email,
#             password=password,
#         )
#         user.staff = True
#         user.admin = True
#         user.save(using=self._db)
#         return user


class User(AbstractUser):
    picture = models.ImageField(
        upload_to='profile_pictures', null=False, blank=False)
    full_name = models.CharField(max_length=100, default="Fullname not set")
    email = models.EmailField(unique=True)

    first_name = None
    last_name = None

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    objects = CustomUserManager()

    def __str__(self):
        return self.email

authentication/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
class UserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('full_name','email','username','password1','password2')

authentication/views.py
from django.shortcuts import render,redirect
from django.views.generic import View
from django.http import HttpResponse
from authentication.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
# Create your views here.

class SignInView(View):
    template_name = 'authentication/signin.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('feed_view')
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        password = request.POST.get('password')
        form = AuthenticationForm(request.POST)

        user = authenticate(request, email = email, password = password)
        if user is None:
            messages.error(request,'Username or Password Invalid')
            return redirect('signin_view')
            # return render(request, self.template_name)

        login(request, user)
        return redirect('feed_view')

class SignUpView(View):
    template_name = 'authentication/signup.html'
    form_class = UserForm

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('feed_view')
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('signin_view')
        context = {'form':form}
        return render(request, self.template_name, context)

class SignOutView(View):
    def post(self, request):
        logout(request)
        return redirect('signin_view')

class PRView(PasswordResetView):
    template_name = 'authentication/password_reset.html'

class PRConfirm(PasswordResetConfirmView):
    template_name = 'authentication/password_reset_confirm.html'

class PRDone(PasswordResetDoneView):
    template_name = 'authentication/password_reset_done.html'

class PRComplete(PasswordResetCompleteView):
    template_name = 'authentication/password_reset_complete.html'

common/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View
from django.http import HttpResponse
from django.contrib.auth import logout

class FeedView(TemplateView):
    template_name = 'core/feed.html'

user/views.py
from django.shortcuts import render

# Create your views here.

authentication/templates/authentication/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />

    <title>Insta Clone</title>

    {% block head %} {% endblock head %}

  </head>
  
  <body>

    {% block content %} {% endblock content %}

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
    {% block javascript %} {% endblock javascript %}
  </body>
</html>

authentication/templates/authentication/password_reset.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/password_reset.css' %}">
{% endblock %}

{% block content %}

<header>
    <nav class="navbar navbar-light bg-white border-bottom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'images/instalogo.png' %}" class="nav__insta__logo">
            </a>
        </div>
    </nav>
</header>

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'images/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Trouble Signin In?</h4></div>
                    <div class="forgot__password__text py-2">
                        Enter your email, phone, or username and we'll send you a link to get back into your account.
                    </div>
                    <div class="mb-3">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="my-1 form__input">
                                <input id="id_email" type="email" name="email" placeholder="Email" required maxlength="240" autocomplete="email">
                            </div>
                            <div class="my-4 mx-auto text-center">
                                <button class="btn btn-sm auth__btn">Send Signin Link</button>
                            </div>
                        </form>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

authentication/templates/authentication/password_reset_complete.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/password_reset.css' %}">
{% endblock %}

{% block content %}

<header>
    <nav class="navbar navbar-light bg-white border-bottom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'images/instalogo.png' %}" class="nav__insta__logo">
            </a>
        </div>
    </nav>
</header>

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'images/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Successfully Reset</h4></div>
                    <div class="forgot__password__text py-2">
                        You can go ahead and signin now.
                        <br>
                        <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">
                            Click here to Sign In.
                        </a>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

authentication/templates/authentication/password_reset_confirm.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/password_reset.css' %}">
{% endblock %}

{% block content %}

<header>
    <nav class="navbar navbar-light bg-white border-bottom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'images/instalogo.png' %}" class="nav__insta__logo">
            </a>
        </div>
    </nav>
</header>

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'images/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Trouble Signin In?</h4></div>
                    <div class="forgot__password__text py-2">
                        Enter your email, phone, or username and we'll send you a link to get back into your account.
                    </div>
                    <div class="mb-3">
                        {% if form %}
                            <div>
                                {% if form.non_field_errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ form.non_field_errors }}
                                    </div>
                                {% endif%}
                            </div>
                            <form method="POST">
                                {% csrf_token %}
                                <div class="my-1 form__input">
                                    <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1" placeholder="Password">
                                    <p>{{ form.new_password1.errors }}</p>
                                </div>
                                <div class="my-1 form__input">
                                    <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2" placeholder="Retype Password">
                                    <p>{{ form.new_password2.errors }}</p>
                                </div>
                                <div class="my-4 mx-auto text-center">
                                    <button class="btn btn-sm auth__btn">Set Password</button>
                                </div>
                            </form>
                        {% else %}
                            <div class="py-2">
                                <strong style="color: #ff6600;">Your password reset link is invalid or expired.</strong>
                            </div>
                        {% endif %}
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

authentication/templates/authentication/password_reset_done.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/password_reset.css' %}">
{% endblock %}

{% block content %}

<header>
    <nav class="navbar navbar-light bg-white border-bottom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'images/instalogo.png' %}" class="nav__insta__logo">
            </a>
        </div>
    </nav>
</header>

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'images/instalogo.png' %}" class="insta__logo mx-auto mt-4 mb-5">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Email Sent.</h4></div>
                    <div class="forgot__password__text py-2">
                        Check your registered email for the Password Reset link.
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

authentication/templates/authentication/password_reset_email.html
Devjunction is trying to steal your pasword- {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
  

authentication/templates/authentication/signin.html
{% extends 'authentication/base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}" />
{% endblock %} {% block content %}

<div class="container my-5">
  <div class="row">
    <div class="col-sm-6 d-none d-md-block">
      <img
        src="{% static 'images/phone_img.png' %}"
        class="signin__phone float-right"
      />
    </div>
    <div class="col-sm-6 my-auto">
      <div class="">
        <div class="text-center card px-5 mr-md-auto signin__card">
          <img
            src="{% static 'images/instalogo.png' %}"
            class="insta__logo mt-4 mb-3 mx-auto"
          />
          <div class="signin">
            <div class="signin__form mb-3">
              <form method="POST">
                {% csrf_token %}
                <div class="my-1 form__input">
                  <input
                    id="id_email"
                    type="email"
                    name="email"
                    placeholder="Email"
                  />
                  {{ form.email.errors }}
                </div>
                <div class="my-1 form__input">
                  <input
                    id="id_password"
                    type="password"
                    name="password"
                    placeholder="Password"
                  />
                  {{ form.password.errors }}
                </div>
                {% for message in messages %}
                <p class="text-danger">{{ message }}</p>
                {% endfor %}
                <div class="my-4 mx-auto text-center">
                  <button class="btn btn-sm auth__btn">Sign in</button>
                </div>
              </form>
            </div>
            <div class="text-center my-4">
              <p class="or__text">OR</p>
            </div>
            <div class="my-1 mx-auto text-center">
              <a
                class="login__fb__text text-decoration-none"
                href="{% url 'signin_view' %}"
                >Log in with Facebook</a
              >
            </div>
            <div class="mb-4">
              <a
                class="forogt__password text-decoration-none"
                href="{% url 'password_reset' %}"
                >Forgot password?</a
              >
            </div>
          </div>
        </div>
        <div class="text-center card mt-2 px-5 mr-md-auto signin__card">
          <p class="have__an__account py-3">
            Don't have an account?
            <a href="{% url 'signup_view' %}" class="text-decoration-none"
              >Sign up</a
            >
          </p>
        </div>
        <div class="text-center mt-2 px-5 mr-auto get__app">
          <p class="">Get the app.</p>
          <div class="row">
            <div class="col-6">
              <img
                src="{% static 'images/appstore.png' %}"
                class="app__download__img"
              />
            </div>
            <div class="col-6">
              <img
                src="{% static 'images/playstore.png' %}"
                class="app__download__img"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

authentication/templates/authentication/signup.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
{% endblock head %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto signup__card">
                <img src="{% static 'images/instalogo.png' %}" class="insta__logo mt-4 mb-3 mx-auto">
                <div class="signup">
                    <p class="signup__card__text">Sign up to see photos and videos from your friends.</p>
                    <div class="my-4 mx-auto text-center">
                        <button class="btn btn-sm auth__btn">Log in with Facebook</button>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div>
                        <!-- {% if form.non_field_errors %} -->
                            <div class="alert alert-danger" role="alert">
                                {{ form.non_field_errors }}
                            </div>
                        <!-- {% endif%} -->
                    </div>
                    <div class="signup__form mb-3">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="my-1 form__input">
                                <input id="id_email" type="email" name="email" placeholder="Email" class="form-control {% if form.email.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.email.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_username" type="text" name="username" placeholder="Username" class="form-control {% if form.username.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.username.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_full_name" type="text" name="full_name" placeholder="Full Name" class="form-control {% if form.full_name.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.full_name.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_password1" type="password" name="password1" placeholder="Password" class="form-control {% if form.password1.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.password1.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_password2" type="password" name="password2" placeholder="Retype Password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.password2.errors }}
                                </div>
                            </div>
                            <div class="my-4 mx-auto text-center">
                                <button class="btn btn-sm auth__btn" type="submit">Sign up</button>
                            </div>
                        </form>
                    </div>
                    <p class="terms__conditions mb-4">By signing up, you agree to our <strong>Terms</strong> , <strong>Data Policy</strong> and <strong>Cookies Policy</strong> .</p>
                </div>
            </div>
            <div class="text-center card mt-2 px-5 mx-auto signup__card">
                <p class="have__an__account py-3">Have an account? <a href="{% url 'signin_view' %}" class="text-decoration-none">Sign in</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/feed.html
{% extends 'authentication/base.html' %}

{% block content %}
<h1>Insta Feed</h1>
<form method="POST" action="{% url 'signout_view' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">LOGOUT</button>
</form>
{% endblock %}